server:
  port: 8009

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/timo?characterEncoding=utf-8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/**
    servlet:
      content-type: text/html # Content-Type 的值
    enabled: true # 启用MVC Thymeleaf视图分辨率
    mode: HTML # 应用于模板的模板模式。另请参见StandardTemplateModeHandlers。
    encoding: UTF-8 # 模板编码
    suffix: .html # 构建URL时附加到查看名称的后缀
    check-template-location: true  # 检查模板位置是否存在。
    cache: false # 模板缓存，开发阶段要使用false

mybatis:
  mapper-locations: classpath:MyBatis/**/*Mapper.xml
  configuration:
    typeAliasesPackage: com.bajiuqu.manage.**.dao
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  params:
    count: countSql
  reasonable: true
  support-methods-arguments: true
