server:
  port: 8848
  servlet:
    context-path: /bajiuqu-nacos

spring:
  application:
    name: NacosService

nacos:
  # nacos服务端的地址
  config:
    server-addr: 127.0.0.1:8848
  # discovery地址
  discovery:
    server-addr: 127.0.0.1:8848

logging:
  config: classpath:log/logback-spring.xml