server:
  port: 8848
  servlet:
    context-path: /bajiuqu-search

spring:
  application:
    name: SearchService

bajiuqu:
  elasticsearch:
    hostname: 192.168.182.131
    port: 9200
    scheme: HTTP
    username: elastic
    password: admin@123