server:
  port: 8848
  servlet:
    context-path: /bajiuqu-nacos

spring:
  application:
    name: SearchService

bajiuqu:
  elasticsearch:
    hostname: 192.168.182.137
    port: 9200
    scheme: HTTP
    username: elastic
    password: nanxihansheng34!

logging:
  config: classpath:log/logback-spring.xml